# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CD
on:
  push:
    branches: [master]
  create:
    tags:
      - "v*.*.*"
permissions:
  contents: read
  packages: write
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
  NG_CLI_ANALYTICS: ci
  NODE_OPTIONS: "--max-old-space-size=8192"
  TERM: xterm
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: modules/api/go.mod
          check-latest: true
          cache-dependency-path: modules/api/go.sum

      - name: Install API dependencies
        working-directory: modules/api
        run: go mod download

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0

      - name: Install web dependencies
        working-directory: modules/web
        run: yarn

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_RELEASE_USER }}
          password: ${{ secrets.DOCKER_RELEASE_PASS }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy development release
        if: github.event_name == 'push' && contains(github.ref, 'master')
        run: PATH=$PATH:$GOPATH/bin make deploy-dev

      - name: Build and deploy official release
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
        run: PATH=$PATH:$GOPATH/bin make deploy
