# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI / Helm
on:
  pull_request:
    paths:
    - 'charts/helm-chart/**'
    - '.github/workflows/ci-helm.yml'
permissions:
  contents: read
jobs:
  helm-lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: Install kubeconform-helm
        run: helm plugin install https://github.com/jtyr/kubeconform-helm

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing lint
        run: ct lint --config=charts/helm-chart/.helm-chart-testing.yaml

      - name: Start kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:v1.28.0

      - name: Deploy prometheus-operator
        run: kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.54.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

      - name: Run chart-testing install
        run: ct install --config=charts/helm-chart/.helm-chart-testing.yaml
